### ISSUE TITLE
Joomla 4-5 compatibility

### ISSUE THREAD

**Issue by micker** [coolcat-creations/blog-tagfilter#10]
Hello this override isn't compatible with joomla 4-5
using jeventdispatcher use old methode
did you plan to update this ? 
@coolcat-creations 
regards

**Comment by coolcat-creations** [comment]
Hi @micker I used this for a presentation 5 years ago, I was not aware anyone was using this at all. I do not really plan to put much effort in it because I use other solutions now. Do you currently need it?

**Comment by micker** [comment]
thanks for this prompt reply, yes i need a solution but i didn't find (sp porfolio isn't compatible for exemple)
share this ! realy appreciate

**Comment by coolcat-creations** [comment]
You need the animated part? Because jfilters works quite great.

**Comment by micker** [comment]
ah jfilters i forgot this solution .... i will check it thanks !
